### ISSUE TITLE
init错误

### ISSUE THREAD

**Issue by mutouzhang** [ljy2010a/go_alipay#1]
`block, _ := pem.Decode([]byte("rsa_private_key.pem"))
    if block == nil {
        fmt.Println("rsaSign private_key error")
    }`
这个block是nil的...pem确实存在且能够打印出来

**Comment by liangjunyu2010** [comment]
估计你用的web的config吧  web 是不需要Init

**Comment by mutouzhang** [comment]
发现问题所在了,传参理解错误，应该是
`block, _ := pem.Decode([]byte(`-----BEGIN RSA PRIVATE KEY-----
......
-----END RSA PRIVATE KEY-----
`))`
感谢解答
